### PR TITLE
Fixed: Quotes removal in `Faker.Internet` functions

### LINKED ISSUE #211: Faker.Internet still generating content with unsafe characters
I don't think the `~s('")` actually removes `'` characters https://github.com/igas/faker/commit/ef4b56fac71488392acba6610e84e438696a1aa3#diff-e3ecc989170f877abe39eb1cdf76c35bR340

```elixir
"foo@b'ar.com" |> String.replace(~s('"), "")
# "foo@b'ar.com"
"foo@b'ar.com" |> String.replace(~s("), "") |> String.replace(~s('), "")
# "foo@bar.com"
```

faker-single-quote
I'm still seeing this on b964ad1aceeff867e0011b994bc97c89e36183bd

PR in the works.

### PR DESCRIPTION
**Pull request by jc00ke**
Moved the implementation to `Faker.Util`.

Fixes #211

I've added:

- [x] CHANGELOG.md

### CODE REVIEW

File: lib/faker/util.ex [hunk 1]
```diff
@@ -273,5 +273,22 @@ defmodule Faker.Util do
...
+
+  ## Examples
+
+      iex> Faker.Util.remove_special_characters("f'oo")
+      "foo"
+      iex> Faker.Util.remove_special_characters(~s(f"o'o))
+      "foo"
+  """
+  @spec remove_special_characters(binary) :: binary
+  def remove_special_characters(string) do
```
Comment (igas) [inline lib/faker/util.ex]: I don't think we should move it out, the name is too generic, we won't be able to reuse it if other characters in other places would be different. Lets keep it in `lib/faker/internet.ex` for now.

File: lib/faker/util.ex [hunk 2]
```diff
@@ -273,5 +273,22 @@ defmodule Faker.Util do
...
+    string
+    |> String.replace(~s("), "")
+    |> String.replace(~s('), "")
```
Comment (igas) [inline lib/faker/util.ex]:
```suggestion
    String.replace(string, ~r/('|")/, "")
```

File: lib/faker/util.ex (hunk 1 above)
Comment (jc00ke) [reply lib/faker/util.ex]: I wasn't able to test it in isolation because it was a private function, which is why I pulled it out. Would you be open to renaming it to `remove_quote_characters` or something like that?

**Comment by jc00ke** [comment]
Hi! Anything else I can add here for this?

**Comment by igas** [comment]
Hi @jc00ke 

I still think it's too specific to move to `Util`, I would keep it private in `Internet` module. I'm not sure what to suggest to test it properly. In ideal world we could test it through other public function, but we don't have one where we do not randomize it.

**Comment by jc00ke** [comment]
Yeah, I can't think of another good way to test it since the functions that use it don't take any input. About the only thing I can think of would be to make a test locale that had a single option for `Name.first_name()` et al with quotes in them. If not that, then I can stick it back in `Internet`, make it private and keep an eye out for regressions.

**Comment by igas** [comment]
Hi @jc00ke,

I pushed a fixed test to master and updated your branch. Please take a look and tell me what you think.

Thanks.

**Comment by jc00ke** [comment]
Looks good to me. I'll keep an eye out for issues in my own test suite. I know I've seen failures lately because of `'` characters but I'm pretty sure it's not from the `Internet` module.
